import Foundation

/// CIE Lab colour difference for sRGB colours (D65, ΔE76). Used to calibrate
/// the tint steps and to map legacy gradients onto them; never at draw time.
enum ColorDifference {
    struct Lab: Equatable {
        let l: Double
        let a: Double
        let b: Double
    }

    private static func linear(_ component: Double) -> Double {
        component <= 0.04045
            ? component / 12.92
            : pow((component + 0.055) / 1.055, 2.4)
    }

    static func lab(_ color: AtticThemeColor) -> Lab {
        let r = linear(min(max(color.red, 0), 1))
        let g = linear(min(max(color.green, 0), 1))
        let b = linear(min(max(color.blue, 0), 1))
        // sRGB (D65) to XYZ, then relative to the D65 white point.
        let x = (0.4124564 * r + 0.3575761 * g + 0.1804375 * b) / 0.95047
        let y = (0.2126729 * r + 0.7151522 * g + 0.0721750 * b) / 1.00000
        let z = (0.0193339 * r + 0.1191920 * g + 0.9503041 * b) / 1.08883
        func f(_ t: Double) -> Double {
            let delta = 6.0 / 29.0
            return t > pow(delta, 3)
                ? cbrt(t)
                : t / (3 * delta * delta) + 4.0 / 29.0
        }
        let fx = f(x), fy = f(y), fz = f(z)
        return Lab(l: 116 * fy - 16, a: 500 * (fx - fy), b: 200 * (fy - fz))
    }

    static func deltaE76(_ first: AtticThemeColor, _ second: AtticThemeColor) -> Double {
        let lhs = lab(first)
        let rhs = lab(second)
        return sqrt(pow(lhs.l - rhs.l, 2) + pow(lhs.a - rhs.a, 2) + pow(lhs.b - rhs.b, 2))
    }
}

/// The Tint wash, calibrated so each step has the same perceived strength on
/// every palette, mode, surface and Depth state.
///
/// The wash is the palette's accent hue at full saturation, fading from its
/// top opacity at the top edge to nothing at `fadeEnd` of the panel height.
/// `table` holds the solved top opacities: for each cell the opacity that
/// produces the step's target ΔE76 between the top-edge composite with and
/// without the wash, then clamped so primary and secondary text keep at
/// least `AtticPanelSurfaceTreatment.readableContrastTarget` over the
/// worst-case composite. The table is generated by `solve` (see
/// `Docs/Appearance-Model-2026-09.md`) and pinned by a unit test that
/// recomputes every cell; nothing solves at draw time.
enum PanelTintCalibration {
    /// Normalised height at which the wash has faded to nothing.
    static let fadeEnd: Double = 0.6
    /// HSV saturation of the wash colour.
    static let saturation: Double = 0.85
    /// HSV value of the wash colour per appearance.
    static func value(for appearance: AtticPanelThemeAppearance) -> Double {
        appearance == .dark ? 0.95 : 1.0
    }

    struct Cell: Equatable, Sendable {
        /// Opacity of the wash at the top edge.
        let topOpacity: Double
        /// ΔE76 the solved opacity actually produces at the top edge.
        let colorDifference: Double
        /// True when the readability floor, not the ΔE target, set the opacity.
        let isClamped: Bool
    }

    struct Key: Hashable, Sendable {
        let theme: AtticPanelTheme
        let appearance: AtticPanelThemeAppearance
        let kind: AtticPanelSurfaceTreatment.Kind
        let depth: Bool
    }

    static func cell(
        theme: AtticPanelTheme,
        appearance: AtticPanelThemeAppearance,
        kind: AtticPanelSurfaceTreatment.Kind,
        depth: Bool,
        level: PanelTintLevel
    ) -> Cell? {
        guard level != .off else { return nil }
        return table[Key(theme: theme, appearance: appearance, kind: kind, depth: depth)]?[level]
    }

    // MARK: Wash colour

    /// The accent's hue at HSV saturation `saturation` and the appearance's
    /// `value`: a saturated version of the palette accent so the wash reads
    /// as colour, not as a lighter or darker surface.
    static func washColor(
        for palette: AtticPanelThemePalette,
        appearance: AtticPanelThemeAppearance
    ) -> AtticThemeColor {
        let hue = hue(of: palette.accent)
        return color(hue: hue, saturation: saturation, value: value(for: appearance))
    }

    static func hue(of color: AtticThemeColor) -> Double {
        let maximum = max(color.red, color.green, color.blue)
        let minimum = min(color.red, color.green, color.blue)
        let delta = maximum - minimum
        guard delta > 0 else { return 0 }
        let sector: Double
        if maximum == color.red {
            sector = ((color.green - color.blue) / delta).truncatingRemainder(dividingBy: 6)
        } else if maximum == color.green {
            sector = (color.blue - color.red) / delta + 2
        } else {
            sector = (color.red - color.green) / delta + 4
        }
        let normalized = sector / 6
        return normalized < 0 ? normalized + 1 : normalized
    }

    static func color(hue: Double, saturation: Double, value: Double) -> AtticThemeColor {
        let h = (hue - floor(hue)) * 6
        let sector = Int(floor(h))
        let f = h - Double(sector)
        let p = value * (1 - saturation)
        let q = value * (1 - saturation * f)
        let t = value * (1 - saturation * (1 - f))
        switch sector {
        case 0: return AtticThemeColor(red: value, green: t, blue: p)
        case 1: return AtticThemeColor(red: q, green: value, blue: p)
        case 2: return AtticThemeColor(red: p, green: value, blue: t)
        case 3: return AtticThemeColor(red: p, green: q, blue: value)
        case 4: return AtticThemeColor(red: t, green: p, blue: value)
        default: return AtticThemeColor(red: value, green: p, blue: q)
        }
    }

    // MARK: Composite model

    /// The backdrop the readability solver assumes: black behind a Light
    /// panel, white behind a Dark one, the two extremes for the fixed
    /// foregrounds. Solid surfaces transmit nothing, so it is irrelevant there.
    static func worstCaseBackdrop(for appearance: AtticPanelThemeAppearance) -> AtticThemeColor {
        let value = appearance == .dark ? 1.0 : 0.0
        return AtticThemeColor(red: value, green: value, blue: value)
    }

    /// The top-edge composite before the wash: the surface over the backdrop
    /// (the foundation for glass, the whole fill for Solid), then the Depth
    /// crown at its top stop when Depth is on.
    static func baseComposite(
        treatment: AtticPanelSurfaceTreatment,
        depth: Bool,
        backdrop: AtticThemeColor
    ) -> AtticThemeColor {
        let surface = backdrop.mixed(with: treatment.palette.opaqueSurface, amount: treatment.foundationOpacity)
        guard depth else { return surface }
        return PanelDepthCrown.composite(over: surface, appearance: treatment.appearance, location: 0)
    }

    static func tintedComposite(
        base: AtticThemeColor,
        wash: AtticThemeColor,
        topOpacity: Double
    ) -> AtticThemeColor {
        base.mixed(with: wash, amount: topOpacity)
    }

    static func minimumForegroundContrast(
        palette: AtticPanelThemePalette,
        over color: AtticThemeColor
    ) -> Double {
        min(palette.primaryForeground.contrastRatio(with: color),
            palette.secondaryForeground.contrastRatio(with: color))
    }

    // MARK: Solver (generation and tests only)

    /// Solves one cell: bisect the top opacity to the target ΔE, then bisect
    /// it down again if the readability floor is not met. Both functions are
    /// monotone in the opacity over [0, 1] for a source-over blend.
    static func solve(
        treatment: AtticPanelSurfaceTreatment,
        depth: Bool,
        level: PanelTintLevel
    ) -> Cell? {
        guard let target = level.targetColorDifference else { return nil }
        let backdrop = worstCaseBackdrop(for: treatment.appearance)
        let base = baseComposite(treatment: treatment, depth: depth, backdrop: backdrop)
        let wash = washColor(for: treatment.palette, appearance: treatment.appearance)
        func difference(_ opacity: Double) -> Double {
            ColorDifference.deltaE76(base, tintedComposite(base: base, wash: wash, topOpacity: opacity))
        }
        func contrast(_ opacity: Double) -> Double {
            minimumForegroundContrast(palette: treatment.palette,
                                      over: tintedComposite(base: base, wash: wash, topOpacity: opacity))
        }

        var lower = 0.0
        var upper = 1.0
        if difference(1) < target {
            upper = 1
        } else {
            for _ in 0..<40 {
                let middle = (lower + upper) / 2
                if difference(middle) < target { lower = middle } else { upper = middle }
            }
        }
        var opacity = upper
        var clamped = false
        let floor = AtticPanelSurfaceTreatment.readableContrastTarget
        if contrast(opacity) < floor {
            clamped = true
            var low = 0.0
            var high = opacity
            for _ in 0..<40 {
                let middle = (low + high) / 2
                if contrast(middle) >= floor { low = middle } else { high = middle }
            }
            opacity = low
        }
        // Whole tenths of a percent are what the table carries; rounding
        // down keeps a clamped cell on the readable side of the floor.
        let stored = clamped
            ? (opacity * 1000).rounded(.down) / 1000
            : (opacity * 1000).rounded() / 1000
        return Cell(
            topOpacity: stored,
            colorDifference: (difference(stored) * 100).rounded() / 100,
            isClamped: clamped
        )
    }

    static func solveTable() -> [Key: [PanelTintLevel: Cell]] {
        var table: [Key: [PanelTintLevel: Cell]] = [:]
        for theme in AtticPanelTheme.allCases {
            for appearance in AtticPanelThemeAppearance.allCases {
                for kind in AtticPanelSurfaceTreatment.Kind.allCases {
                    for depth in [false, true] {
                        let treatment = theme.surfaceTreatment(
                            appearance: appearance, contrast: .standard,
                            surface: PanelSurfaceStyle(kind), depth: depth, tint: .off,
                            reduceTransparency: false
                        )
                        var cells: [PanelTintLevel: Cell] = [:]
                        for level in PanelTintLevel.allCases {
                            if let cell = solve(treatment: treatment, depth: depth, level: level) {
                                cells[level] = cell
                            }
                        }
                        table[Key(theme: theme, appearance: appearance, kind: kind, depth: depth)] = cells
                    }
                }
            }
        }
        return table
    }

    /// Swift source for `table` and `clampedCellDescriptions`, in the order
    /// the file lists them.
    static func swiftSource(for table: [Key: [PanelTintLevel: Cell]]) -> String {
        var lines: [String] = ["    static let table: [Key: [PanelTintLevel: Cell]] = ["]
        var clamped: [String] = []
        for theme in AtticPanelTheme.allCases {
            for appearance in AtticPanelThemeAppearance.allCases {
                for kind in AtticPanelSurfaceTreatment.Kind.allCases {
                    for depth in [false, true] {
                        let key = Key(theme: theme, appearance: appearance, kind: kind, depth: depth)
                        guard let cells = table[key] else { continue }
                        let levels = [PanelTintLevel.subtle, .vivid, .bold].compactMap { level -> String? in
                            guard let cell = cells[level] else { return nil }
                            if cell.isClamped {
                                clamped.append("\(theme.rawValue) \(appearance.rawValue) \(kind.rawValue) depth=\(depth) \(level.rawValue)")
                            }
                            return String(
                                format: ".%@: c(%.3f, %.2f%@)",
                                level.rawValue, cell.topOpacity, cell.colorDifference,
                                cell.isClamped ? ", clamped: true" : ""
                            )
                        }
                        lines.append(String(
                            format: "        k(.%@, .%@, .%@, %@): [%@],",
                            theme.rawValue, appearance.rawValue, kind.rawValue,
                            depth ? "true" : "false", levels.joined(separator: ", ")
                        ))
                    }
                }
            }
        }
        lines.append("    ]")
        lines.append("")
        lines.append("    static let clampedCellDescriptions: [String] = [")
        lines.append(contentsOf: clamped.map { "        \"\($0)\"," })
        lines.append("    ]")
        return lines.joined(separator: "\n")
    }

    // MARK: Generated table

    private static func k(
        _ theme: AtticPanelTheme,
        _ appearance: AtticPanelThemeAppearance,
        _ kind: AtticPanelSurfaceTreatment.Kind,
        _ depth: Bool
    ) -> Key {
        Key(theme: theme, appearance: appearance, kind: kind, depth: depth)
    }

    private static func c(_ topOpacity: Double, _ colorDifference: Double, clamped: Bool = false) -> Cell {
        Cell(topOpacity: topOpacity, colorDifference: colorDifference, isClamped: clamped)
    }

    // GENERATED by PanelTintCalibration.solveTable(); do not edit by hand.
    // Regenerate by running PanelTintCalibrationTests with
    // ATTIC_PRINT_TINT_TABLE=1 and pasting the printed source here.
    static let table: [Key: [PanelTintLevel: Cell]] = [
        k(.original, .light, .solid, false): [.subtle: c(0.035, 2.98), .vivid: c(0.082, 6.98), .bold: c(0.141, 12.02)],
        k(.original, .light, .solid, true): [.subtle: c(0.035, 2.98), .vivid: c(0.082, 6.98), .bold: c(0.141, 12.02)],
        k(.original, .light, .glass, false): [.subtle: c(0.023, 1.83, clamped: true), .vivid: c(0.023, 1.83, clamped: true), .bold: c(0.023, 1.83, clamped: true)],
        k(.original, .light, .glass, true): [.subtle: c(0.036, 2.97), .vivid: c(0.085, 7.02), .bold: c(0.145, 11.98)],
        k(.original, .light, .frosted, false): [.subtle: c(0.023, 1.83, clamped: true), .vivid: c(0.023, 1.83, clamped: true), .bold: c(0.023, 1.83, clamped: true)],
        k(.original, .light, .frosted, true): [.subtle: c(0.036, 2.97), .vivid: c(0.085, 7.02), .bold: c(0.145, 11.98)],
        k(.original, .dark, .solid, false): [.subtle: c(0.027, 2.99), .vivid: c(0.065, 6.96), .bold: c(0.116, 11.99)],
        k(.original, .dark, .solid, true): [.subtle: c(0.046, 3.04), .vivid: c(0.083, 7.00), .bold: c(0.122, 12.04)],
        k(.original, .dark, .glass, false): [.subtle: c(0.011, 0.87, clamped: true), .vivid: c(0.011, 0.87, clamped: true), .bold: c(0.011, 0.87, clamped: true)],
        k(.original, .dark, .glass, true): [.subtle: c(0.029, 3.02), .vivid: c(0.066, 7.04), .bold: c(0.115, 11.98)],
        k(.original, .dark, .frosted, false): [.subtle: c(0.011, 0.87, clamped: true), .vivid: c(0.011, 0.87, clamped: true), .bold: c(0.011, 0.87, clamped: true)],
        k(.original, .dark, .frosted, true): [.subtle: c(0.029, 3.02), .vivid: c(0.066, 7.04), .bold: c(0.115, 11.98)],
        k(.midnightCobalt, .light, .solid, false): [.subtle: c(0.033, 2.96), .vivid: c(0.078, 7.01), .bold: c(0.133, 11.99)],
        k(.midnightCobalt, .light, .solid, true): [.subtle: c(0.032, 3.02), .vivid: c(0.074, 6.99), .bold: c(0.127, 12.03)],
        k(.midnightCobalt, .light, .glass, false): [.subtle: c(0.029, 2.50, clamped: true), .vivid: c(0.029, 2.50, clamped: true), .bold: c(0.029, 2.50, clamped: true)],
        k(.midnightCobalt, .light, .glass, true): [.subtle: c(0.032, 2.96), .vivid: c(0.076, 7.04), .bold: c(0.129, 11.98)],
        k(.midnightCobalt, .light, .frosted, false): [.subtle: c(0.029, 2.50, clamped: true), .vivid: c(0.029, 2.50, clamped: true), .bold: c(0.029, 2.50, clamped: true)],
        k(.midnightCobalt, .light, .frosted, true): [.subtle: c(0.032, 2.96), .vivid: c(0.076, 7.04), .bold: c(0.129, 11.98)],
        k(.midnightCobalt, .dark, .solid, false): [.subtle: c(0.024, 3.03), .vivid: c(0.056, 6.97), .bold: c(0.102, 11.95)],
        k(.midnightCobalt, .dark, .solid, true): [.subtle: c(0.037, 2.96), .vivid: c(0.069, 6.95), .bold: c(0.101, 11.99)],
        k(.midnightCobalt, .dark, .glass, false): [.subtle: c(0.032, 3.01), .vivid: c(0.075, 7.05), .bold: c(0.128, 12.03)],
        k(.midnightCobalt, .dark, .glass, true): [.subtle: c(0.023, 3.00), .vivid: c(0.052, 6.94), .bold: c(0.091, 11.99)],
        k(.midnightCobalt, .dark, .frosted, false): [.subtle: c(0.032, 3.01), .vivid: c(0.075, 7.05), .bold: c(0.128, 12.03)],
        k(.midnightCobalt, .dark, .frosted, true): [.subtle: c(0.023, 3.00), .vivid: c(0.052, 6.94), .bold: c(0.091, 11.99)],
        k(.porcelainVapor, .light, .solid, false): [.subtle: c(0.043, 3.03), .vivid: c(0.100, 7.00), .bold: c(0.173, 11.98)],
        k(.porcelainVapor, .light, .solid, true): [.subtle: c(0.042, 2.97), .vivid: c(0.100, 7.03), .bold: c(0.172, 11.97)],
        k(.porcelainVapor, .light, .glass, false): [.subtle: c(0.043, 2.98), .vivid: c(0.103, 7.00), .bold: c(0.182, 12.01)],
        k(.porcelainVapor, .light, .glass, true): [.subtle: c(0.044, 3.02), .vivid: c(0.103, 7.01), .bold: c(0.179, 12.02)],
        k(.porcelainVapor, .light, .frosted, false): [.subtle: c(0.043, 2.98), .vivid: c(0.103, 7.00), .bold: c(0.182, 12.01)],
        k(.porcelainVapor, .light, .frosted, true): [.subtle: c(0.044, 3.02), .vivid: c(0.103, 7.01), .bold: c(0.179, 12.02)],
        k(.porcelainVapor, .dark, .solid, false): [.subtle: c(0.034, 3.04), .vivid: c(0.081, 7.02), .bold: c(0.143, 12.00)],
        k(.porcelainVapor, .dark, .solid, true): [.subtle: c(0.044, 2.98), .vivid: c(0.082, 6.96), .bold: c(0.130, 11.96)],
        k(.porcelainVapor, .dark, .glass, false): [.subtle: c(0.001, 0.07, clamped: true), .vivid: c(0.001, 0.07, clamped: true), .bold: c(0.001, 0.07, clamped: true)],
        k(.porcelainVapor, .dark, .glass, true): [.subtle: c(0.030, 3.03), .vivid: c(0.070, 7.02), .bold: c(0.124, 11.99)],
        k(.porcelainVapor, .dark, .frosted, false): [.subtle: c(0.001, 0.07, clamped: true), .vivid: c(0.001, 0.07, clamped: true), .bold: c(0.001, 0.07, clamped: true)],
        k(.porcelainVapor, .dark, .frosted, true): [.subtle: c(0.030, 3.03), .vivid: c(0.070, 7.02), .bold: c(0.124, 11.99)],
        k(.smokedUmber, .light, .solid, false): [.subtle: c(0.040, 2.99), .vivid: c(0.093, 6.98), .bold: c(0.159, 12.01)],
        k(.smokedUmber, .light, .solid, true): [.subtle: c(0.038, 2.97), .vivid: c(0.089, 6.98), .bold: c(0.152, 12.00)],
        k(.smokedUmber, .light, .glass, false): [.subtle: c(0.036, 2.99), .vivid: c(0.084, 6.99), .bold: c(0.144, 11.99)],
        k(.smokedUmber, .light, .glass, true): [.subtle: c(0.039, 3.03), .vivid: c(0.090, 7.03), .bold: c(0.153, 12.01)],
        k(.smokedUmber, .light, .frosted, false): [.subtle: c(0.036, 2.99), .vivid: c(0.084, 6.99), .bold: c(0.144, 11.99)],
        k(.smokedUmber, .light, .frosted, true): [.subtle: c(0.039, 3.03), .vivid: c(0.090, 7.03), .bold: c(0.153, 12.01)],
        k(.smokedUmber, .dark, .solid, false): [.subtle: c(0.023, 2.95), .vivid: c(0.054, 7.06), .bold: c(0.093, 12.00)],
        k(.smokedUmber, .dark, .solid, true): [.subtle: c(0.041, 3.03), .vivid: c(0.081, 7.04), .bold: c(0.116, 11.93)],
        k(.smokedUmber, .dark, .glass, false): [.subtle: c(0.023, 2.04, clamped: true), .vivid: c(0.023, 2.04, clamped: true), .bold: c(0.023, 2.04, clamped: true)],
        k(.smokedUmber, .dark, .glass, true): [.subtle: c(0.026, 3.00), .vivid: c(0.056, 7.03), .bold: c(0.094, 12.02)],
        k(.smokedUmber, .dark, .frosted, false): [.subtle: c(0.023, 2.04, clamped: true), .vivid: c(0.023, 2.04, clamped: true), .bold: c(0.023, 2.04, clamped: true)],
        k(.smokedUmber, .dark, .frosted, true): [.subtle: c(0.026, 3.00), .vivid: c(0.056, 7.03), .bold: c(0.094, 12.02)],
        k(.electricBlue, .light, .solid, false): [.subtle: c(0.036, 2.96), .vivid: c(0.085, 7.00), .bold: c(0.146, 12.02)],
        k(.electricBlue, .light, .solid, true): [.subtle: c(0.036, 3.01), .vivid: c(0.084, 7.02), .bold: c(0.144, 12.04)],
        k(.electricBlue, .light, .glass, false): [.subtle: c(0.039, 3.02), .vivid: c(0.044, 3.41, clamped: true), .bold: c(0.044, 3.41, clamped: true)],
        k(.electricBlue, .light, .glass, true): [.subtle: c(0.037, 3.01), .vivid: c(0.086, 6.98), .bold: c(0.148, 12.01)],
        k(.electricBlue, .light, .frosted, false): [.subtle: c(0.039, 3.02), .vivid: c(0.044, 3.41, clamped: true), .bold: c(0.044, 3.41, clamped: true)],
        k(.electricBlue, .light, .frosted, true): [.subtle: c(0.037, 3.01), .vivid: c(0.086, 6.98), .bold: c(0.148, 12.01)],
        k(.electricBlue, .dark, .solid, false): [.subtle: c(0.028, 3.05), .vivid: c(0.068, 6.98), .bold: c(0.122, 12.00)],
        k(.electricBlue, .dark, .solid, true): [.subtle: c(0.046, 3.01), .vivid: c(0.084, 7.05), .bold: c(0.124, 11.97)],
        k(.electricBlue, .dark, .glass, false): [.subtle: c(0.016, 1.20, clamped: true), .vivid: c(0.016, 1.20, clamped: true), .bold: c(0.016, 1.20, clamped: true)],
        k(.electricBlue, .dark, .glass, true): [.subtle: c(0.029, 2.99), .vivid: c(0.067, 6.98), .bold: c(0.119, 12.03)],
        k(.electricBlue, .dark, .frosted, false): [.subtle: c(0.016, 1.20, clamped: true), .vivid: c(0.016, 1.20, clamped: true), .bold: c(0.016, 1.20, clamped: true)],
        k(.electricBlue, .dark, .frosted, true): [.subtle: c(0.029, 2.99), .vivid: c(0.067, 6.98), .bold: c(0.119, 12.03)],
        k(.seaGlass, .light, .solid, false): [.subtle: c(0.038, 2.99), .vivid: c(0.090, 7.02), .bold: c(0.155, 11.97)],
        k(.seaGlass, .light, .solid, true): [.subtle: c(0.037, 2.97), .vivid: c(0.088, 7.03), .bold: c(0.151, 11.96)],
        k(.seaGlass, .light, .glass, false): [.subtle: c(0.033, 2.98), .vivid: c(0.079, 7.04), .bold: c(0.137, 12.00)],
        k(.seaGlass, .light, .glass, true): [.subtle: c(0.037, 2.98), .vivid: c(0.087, 6.96), .bold: c(0.151, 11.97)],
        k(.seaGlass, .light, .frosted, false): [.subtle: c(0.033, 2.98), .vivid: c(0.079, 7.04), .bold: c(0.137, 12.00)],
        k(.seaGlass, .light, .frosted, true): [.subtle: c(0.037, 2.98), .vivid: c(0.087, 6.96), .bold: c(0.151, 11.97)],
        k(.seaGlass, .dark, .solid, false): [.subtle: c(0.024, 2.97), .vivid: c(0.058, 7.00), .bold: c(0.102, 11.96)],
        k(.seaGlass, .dark, .solid, true): [.subtle: c(0.036, 2.99), .vivid: c(0.069, 6.96), .bold: c(0.100, 12.00)],
        k(.seaGlass, .dark, .glass, false): [.subtle: c(0.005, 0.46, clamped: true), .vivid: c(0.005, 0.46, clamped: true), .bold: c(0.005, 0.46, clamped: true)],
        k(.seaGlass, .dark, .glass, true): [.subtle: c(0.023, 2.98), .vivid: c(0.051, 6.97), .bold: c(0.091, 12.03)],
        k(.seaGlass, .dark, .frosted, false): [.subtle: c(0.005, 0.46, clamped: true), .vivid: c(0.005, 0.46, clamped: true), .bold: c(0.005, 0.46, clamped: true)],
        k(.seaGlass, .dark, .frosted, true): [.subtle: c(0.023, 2.98), .vivid: c(0.051, 6.97), .bold: c(0.091, 12.03)],
        k(.amethyst, .light, .solid, false): [.subtle: c(0.024, 3.03), .vivid: c(0.055, 6.97), .bold: c(0.094, 11.96)],
        k(.amethyst, .light, .solid, true): [.subtle: c(0.023, 2.98), .vivid: c(0.054, 7.02), .bold: c(0.092, 12.02)],
        k(.amethyst, .light, .glass, false): [.subtle: c(0.024, 3.05), .vivid: c(0.030, 3.82, clamped: true), .bold: c(0.030, 3.82, clamped: true)],
        k(.amethyst, .light, .glass, true): [.subtle: c(0.023, 2.96), .vivid: c(0.054, 6.97), .bold: c(0.093, 12.06)],
        k(.amethyst, .light, .frosted, false): [.subtle: c(0.024, 3.05), .vivid: c(0.030, 3.82, clamped: true), .bold: c(0.030, 3.82, clamped: true)],
        k(.amethyst, .light, .frosted, true): [.subtle: c(0.023, 2.96), .vivid: c(0.054, 6.97), .bold: c(0.093, 12.06)],
        k(.amethyst, .dark, .solid, false): [.subtle: c(0.020, 2.98), .vivid: c(0.048, 7.04), .bold: c(0.083, 11.97)],
        k(.amethyst, .dark, .solid, true): [.subtle: c(0.033, 3.02), .vivid: c(0.064, 7.03), .bold: c(0.093, 11.99)],
        k(.amethyst, .dark, .glass, false): [.subtle: c(0.024, 2.97), .vivid: c(0.056, 6.95), .bold: c(0.097, 12.04)],
        k(.amethyst, .dark, .glass, true): [.subtle: c(0.020, 2.98), .vivid: c(0.044, 6.98), .bold: c(0.074, 12.01)],
        k(.amethyst, .dark, .frosted, false): [.subtle: c(0.024, 2.97), .vivid: c(0.056, 6.95), .bold: c(0.097, 12.04)],
        k(.amethyst, .dark, .frosted, true): [.subtle: c(0.020, 2.98), .vivid: c(0.044, 6.98), .bold: c(0.074, 12.01)],
    ]

    /// The cells whose opacity the readability floor set, in the test's
    /// "theme appearance kind depth=… level" form. Generated with the table.
    static let clampedCellDescriptions: [String] = [
        "original light glass depth=false subtle",
        "original light glass depth=false vivid",
        "original light glass depth=false bold",
        "original light frosted depth=false subtle",
        "original light frosted depth=false vivid",
        "original light frosted depth=false bold",
        "original dark glass depth=false subtle",
        "original dark glass depth=false vivid",
        "original dark glass depth=false bold",
        "original dark frosted depth=false subtle",
        "original dark frosted depth=false vivid",
        "original dark frosted depth=false bold",
        "midnightCobalt light glass depth=false subtle",
        "midnightCobalt light glass depth=false vivid",
        "midnightCobalt light glass depth=false bold",
        "midnightCobalt light frosted depth=false subtle",
        "midnightCobalt light frosted depth=false vivid",
        "midnightCobalt light frosted depth=false bold",
        "porcelainVapor dark glass depth=false subtle",
        "porcelainVapor dark glass depth=false vivid",
        "porcelainVapor dark glass depth=false bold",
        "porcelainVapor dark frosted depth=false subtle",
        "porcelainVapor dark frosted depth=false vivid",
        "porcelainVapor dark frosted depth=false bold",
        "smokedUmber dark glass depth=false subtle",
        "smokedUmber dark glass depth=false vivid",
        "smokedUmber dark glass depth=false bold",
        "smokedUmber dark frosted depth=false subtle",
        "smokedUmber dark frosted depth=false vivid",
        "smokedUmber dark frosted depth=false bold",
        "electricBlue light glass depth=false vivid",
        "electricBlue light glass depth=false bold",
        "electricBlue light frosted depth=false vivid",
        "electricBlue light frosted depth=false bold",
        "electricBlue dark glass depth=false subtle",
        "electricBlue dark glass depth=false vivid",
        "electricBlue dark glass depth=false bold",
        "electricBlue dark frosted depth=false subtle",
        "electricBlue dark frosted depth=false vivid",
        "electricBlue dark frosted depth=false bold",
        "seaGlass dark glass depth=false subtle",
        "seaGlass dark glass depth=false vivid",
        "seaGlass dark glass depth=false bold",
        "seaGlass dark frosted depth=false subtle",
        "seaGlass dark frosted depth=false vivid",
        "seaGlass dark frosted depth=false bold",
        "amethyst light glass depth=false vivid",
        "amethyst light glass depth=false bold",
        "amethyst light frosted depth=false vivid",
        "amethyst light frosted depth=false bold",
    ]
}
