import Foundation

/// CIE Lab colour difference for sRGB colours (D65, ΔE76). Used to calibrate
/// the tint steps and to map legacy gradients onto them; never at draw time.
enum ColorDifference {
    struct Lab: Equatable {
        let l: Double
        let a: Double
        let b: Double
    }

    private static func linear(_ component: Double) -> Double {
        component <= 0.04045
            ? component / 12.92
            : pow((component + 0.055) / 1.055, 2.4)
    }

    static func lab(_ color: AtticThemeColor) -> Lab {
        let r = linear(min(max(color.red, 0), 1))
        let g = linear(min(max(color.green, 0), 1))
        let b = linear(min(max(color.blue, 0), 1))
        // sRGB (D65) to XYZ, then relative to the D65 white point.
        let x = (0.4124564 * r + 0.3575761 * g + 0.1804375 * b) / 0.95047
        let y = (0.2126729 * r + 0.7151522 * g + 0.0721750 * b) / 1.00000
        let z = (0.0193339 * r + 0.1191920 * g + 0.9503041 * b) / 1.08883
        func f(_ t: Double) -> Double {
            let delta = 6.0 / 29.0
            return t > pow(delta, 3)
                ? cbrt(t)
                : t / (3 * delta * delta) + 4.0 / 29.0
        }
        let fx = f(x), fy = f(y), fz = f(z)
        return Lab(l: 116 * fy - 16, a: 500 * (fx - fy), b: 200 * (fy - fz))
    }

    static func deltaE76(_ first: AtticThemeColor, _ second: AtticThemeColor) -> Double {
        let lhs = lab(first)
        let rhs = lab(second)
        return sqrt(pow(lhs.l - rhs.l, 2) + pow(lhs.a - rhs.a, 2) + pow(lhs.b - rhs.b, 2))
    }
}

/// The Tint wash, calibrated so each step has the same perceived strength on
/// every palette, mode and surface.
///
/// The wash is the palette's accent hue at full saturation, fading from its
/// top opacity at the top edge to nothing at `fadeEnd` of the panel height.
/// `table` holds the tint-aware foundation and top opacities: for each cell
/// the smallest whole-percent foundation at or above Tint Off that lets the
/// wash hit its target ΔE76 while primary and secondary text keep at least
/// `AtticPanelSurfaceTreatment.readableContrastTarget` over the worst-case
/// measured native-surface underlay. The table is generated by `solve` (see
/// `Docs/Appearance-Model-2026-09.md`) and pinned by a unit test that
/// recomputes every cell; nothing solves at draw time.
enum PanelTintCalibration {
    /// Normalised height at which the wash has faded to nothing.
    static let fadeEnd: Double = 0.6
    /// HSV saturation of the wash colour.
    static let saturation: Double = 0.85
    /// HSV value of the wash colour per appearance.
    static func value(for appearance: AtticPanelThemeAppearance) -> Double {
        appearance == .dark ? 0.95 : 1.0
    }

    struct Cell: Equatable, Sendable {
        /// Opacity of the readable foundation under the wash.
        let foundationOpacity: Double
        /// Opacity of the wash at the top edge.
        let topOpacity: Double
        /// ΔE76 the solved opacity actually produces at the top edge.
        let colorDifference: Double
        /// True when the readability floor, not the ΔE target, set the opacity.
        let isClamped: Bool
    }

    struct Key: Hashable, Sendable {
        let theme: AtticPanelTheme
        let appearance: AtticPanelThemeAppearance
        let kind: AtticPanelSurfaceTreatment.Kind
    }

    static func cell(
        theme: AtticPanelTheme,
        appearance: AtticPanelThemeAppearance,
        kind: AtticPanelSurfaceTreatment.Kind,
        level: PanelTintLevel
    ) -> Cell? {
        guard level != .off else { return nil }
        return table[Key(theme: theme, appearance: appearance, kind: kind)]?[level]
    }

    // MARK: Wash colour

    /// The accent's hue at HSV saturation `saturation` and the appearance's
    /// `value`: a saturated version of the palette accent so the wash reads
    /// as colour, not as a lighter or darker surface.
    static func washColor(
        for palette: AtticPanelThemePalette,
        appearance: AtticPanelThemeAppearance
    ) -> AtticThemeColor {
        let hue = hue(of: palette.accent)
        return color(hue: hue, saturation: saturation, value: value(for: appearance))
    }

    static func hue(of color: AtticThemeColor) -> Double {
        let maximum = max(color.red, color.green, color.blue)
        let minimum = min(color.red, color.green, color.blue)
        let delta = maximum - minimum
        guard delta > 0 else { return 0 }
        let sector: Double
        if maximum == color.red {
            sector = ((color.green - color.blue) / delta).truncatingRemainder(dividingBy: 6)
        } else if maximum == color.green {
            sector = (color.blue - color.red) / delta + 2
        } else {
            sector = (color.red - color.green) / delta + 4
        }
        let normalized = sector / 6
        return normalized < 0 ? normalized + 1 : normalized
    }

    static func color(hue: Double, saturation: Double, value: Double) -> AtticThemeColor {
        let h = (hue - floor(hue)) * 6
        let sector = Int(floor(h))
        let f = h - Double(sector)
        let p = value * (1 - saturation)
        let q = value * (1 - saturation * f)
        let t = value * (1 - saturation * (1 - f))
        switch sector {
        case 0: return AtticThemeColor(red: value, green: t, blue: p)
        case 1: return AtticThemeColor(red: q, green: value, blue: p)
        case 2: return AtticThemeColor(red: p, green: value, blue: t)
        case 3: return AtticThemeColor(red: p, green: q, blue: value)
        case 4: return AtticThemeColor(red: t, green: p, blue: value)
        default: return AtticThemeColor(red: value, green: p, blue: q)
        }
    }

    // MARK: Composite model

    /// The raw desktop extreme used by the pre-macOS-26 fallback path and by
    /// tests that deliberately bypass the native-surface credit.
    static func worstCaseBackdrop(for appearance: AtticPanelThemeAppearance) -> AtticThemeColor {
        let value = appearance == .dark ? 1.0 : 0.0
        return AtticThemeColor(red: value, green: value, blue: value)
    }

    /// The top-edge composite before the wash.
    static func baseComposite(
        palette: AtticPanelThemePalette,
        foundationOpacity: Double,
        backdrop: AtticThemeColor
    ) -> AtticThemeColor {
        backdrop.mixed(with: palette.opaqueSurface, amount: foundationOpacity)
    }

    static func tintedComposite(
        base: AtticThemeColor,
        wash: AtticThemeColor,
        topOpacity: Double
    ) -> AtticThemeColor {
        base.mixed(with: wash, amount: topOpacity)
    }

    static func minimumForegroundContrast(
        palette: AtticPanelThemePalette,
        over color: AtticThemeColor
    ) -> Double {
        min(palette.primaryForeground.contrastRatio(with: color),
            palette.secondaryForeground.contrastRatio(with: color))
    }

    // MARK: Solver (generation and tests only)

    /// Solves one cell by walking whole-percent foundations from the Tint-Off
    /// minimum upward. At each foundation it solves the wash opacity to the
    /// target ΔE, then accepts the first combination that keeps both text
    /// colours at or above the readability floor.
    static func solve(
        theme: AtticPanelTheme,
        appearance: AtticPanelThemeAppearance,
        kind: AtticPanelSurfaceTreatment.Kind,
        palette: AtticPanelThemePalette,
        level: PanelTintLevel,
        minimumFoundationOpacity: Double,
        creditsNativeSurface: Bool
    ) -> Cell? {
        guard let target = level.targetColorDifference else { return nil }
        let floor = AtticPanelSurfaceTreatment.readableContrastTarget
        let backdrop = AtticPanelSurfaceTreatment.worstCaseUnderlay(
            kind: kind,
            appearance: appearance,
            creditsNativeSurface: creditsNativeSurface
        )
        let wash = washColor(for: palette, appearance: appearance)
        let startPercent = Int(ceil(minimumFoundationOpacity * 100 - 0.000_000_1))

        for percent in startPercent...100 {
            let foundation = Double(percent) / 100
            let base = baseComposite(
                palette: palette,
                foundationOpacity: foundation,
                backdrop: backdrop
            )
            func difference(_ opacity: Double) -> Double {
                ColorDifference.deltaE76(base, tintedComposite(base: base, wash: wash, topOpacity: opacity))
            }

            var lower = 0.0
            var upper = 1.0
            if difference(1) >= target {
                for _ in 0..<40 {
                    let middle = (lower + upper) / 2
                    if difference(middle) < target { lower = middle } else { upper = middle }
                }
            }
            // Judge readability at the opacity the table stores, not the
            // unrounded one: rounding up can otherwise cross the floor.
            let storedOpacity = (upper * 1000).rounded() / 1000
            let tinted = tintedComposite(base: base, wash: wash, topOpacity: storedOpacity)
            if minimumForegroundContrast(palette: palette, over: tinted) >= floor {
                return Cell(
                    foundationOpacity: foundation,
                    topOpacity: storedOpacity,
                    colorDifference: (difference(storedOpacity) * 100).rounded() / 100,
                    isClamped: false
                )
            }
        }

        // Preserve the historical clamp fallback for a future pathological
        // palette. The generated credited table is required to contain none.
        let foundation = 1.0
        let base = baseComposite(palette: palette, foundationOpacity: foundation, backdrop: backdrop)
        func difference(_ opacity: Double) -> Double {
            ColorDifference.deltaE76(base, tintedComposite(base: base, wash: wash, topOpacity: opacity))
        }
        func contrast(_ opacity: Double) -> Double {
            minimumForegroundContrast(palette: palette,
                                      over: tintedComposite(base: base, wash: wash, topOpacity: opacity))
        }
        var lower = 0.0
        var targetOpacity = 1.0
        if difference(1) >= target {
            var upper = 1.0
            for _ in 0..<40 {
                let middle = (lower + upper) / 2
                if difference(middle) < target { lower = middle } else { upper = middle }
            }
            targetOpacity = upper
        }
        var low = 0.0
        var high = targetOpacity
        if contrast(targetOpacity) < floor {
            for _ in 0..<40 {
                let middle = (low + high) / 2
                if contrast(middle) >= floor { low = middle } else { high = middle }
            }
        } else {
            low = targetOpacity
        }
        let stored = (low * 1000).rounded(.down) / 1000
        return Cell(
            foundationOpacity: foundation,
            topOpacity: stored,
            colorDifference: (difference(stored) * 100).rounded() / 100,
            isClamped: true
        )
    }

    static func solveTable() -> [Key: [PanelTintLevel: Cell]] {
        var table: [Key: [PanelTintLevel: Cell]] = [:]
        for theme in AtticPanelTheme.allCases {
            for appearance in AtticPanelThemeAppearance.allCases {
                for kind in AtticPanelSurfaceTreatment.Kind.allCases {
                    let palette = theme.palette(for: appearance)
                    let minimum = kind == .solid ? 1 : AtticPanelSurfaceTreatment.minimumReadableOpacity(
                        palette: palette, appearance: appearance, kind: kind, creditsNativeSurface: true
                    )
                    var cells: [PanelTintLevel: Cell] = [:]
                    for level in PanelTintLevel.allCases {
                        if let cell = solve(
                            theme: theme,
                            appearance: appearance,
                            kind: kind,
                            palette: palette,
                            level: level,
                            minimumFoundationOpacity: minimum,
                            creditsNativeSurface: true
                        ) {
                            cells[level] = cell
                        }
                    }
                    table[Key(theme: theme, appearance: appearance, kind: kind)] = cells
                }
            }
        }
        return table
    }

    /// Swift source for `table` and `clampedCellDescriptions`, in the order
    /// the file lists them.
    static func swiftSource(for table: [Key: [PanelTintLevel: Cell]]) -> String {
        var lines: [String] = ["    static let table: [Key: [PanelTintLevel: Cell]] = ["]
        var clamped: [String] = []
        for theme in AtticPanelTheme.allCases {
            for appearance in AtticPanelThemeAppearance.allCases {
                for kind in AtticPanelSurfaceTreatment.Kind.allCases {
                    let key = Key(theme: theme, appearance: appearance, kind: kind)
                    guard let cells = table[key] else { continue }
                    let levels = [PanelTintLevel.subtle, .vivid, .bold].compactMap { level -> String? in
                        guard let cell = cells[level] else { return nil }
                        if cell.isClamped {
                            clamped.append("\(theme.rawValue) \(appearance.rawValue) \(kind.rawValue) \(level.rawValue)")
                        }
                        return String(
                            format: ".%@: c(%.2f, %.3f, %.2f%@)",
                            level.rawValue,
                            cell.foundationOpacity,
                            cell.topOpacity,
                            cell.colorDifference,
                            cell.isClamped ? ", clamped: true" : ""
                        )
                    }
                    lines.append(String(
                        format: "        k(.%@, .%@, .%@): [%@],",
                        theme.rawValue,
                        appearance.rawValue,
                        kind.rawValue,
                        levels.joined(separator: ", ")
                    ))
                }
            }
        }
        lines.append("    ]")
        lines.append("")
        lines.append("    static let clampedCellDescriptions: [String] = [")
        lines.append(contentsOf: clamped.map { "        \"\($0)\"," })
        lines.append("    ]")
        return lines.joined(separator: "\n")
    }

    // MARK: Generated table

    private static func k(
        _ theme: AtticPanelTheme,
        _ appearance: AtticPanelThemeAppearance,
        _ kind: AtticPanelSurfaceTreatment.Kind
    ) -> Key {
        Key(theme: theme, appearance: appearance, kind: kind)
    }

    private static func c(
        _ foundationOpacity: Double,
        _ topOpacity: Double,
        _ colorDifference: Double,
        clamped: Bool = false
    ) -> Cell {
        Cell(
            foundationOpacity: foundationOpacity,
            topOpacity: topOpacity,
            colorDifference: colorDifference,
            isClamped: clamped
        )
    }

    // GENERATED by PanelTintCalibration.solveTable(); do not edit by hand.
    // Regenerate by running PanelTintCalibrationTests with
    // ATTIC_PRINT_TINT_TABLE=1 and pasting the printed source here.
    static let table: [Key: [PanelTintLevel: Cell]] = [
        k(.original, .light, .solid): [.subtle: c(1.00, 0.035, 2.98), .vivid: c(1.00, 0.082, 6.98), .bold: c(1.00, 0.141, 12.02)],
        k(.original, .light, .glass): [.subtle: c(0.23, 0.038, 3.02), .vivid: c(0.24, 0.089, 7.02), .bold: c(0.24, 0.153, 11.98)],
        k(.original, .light, .frosted): [.subtle: c(0.30, 0.038, 3.02), .vivid: c(0.31, 0.089, 7.02), .bold: c(0.31, 0.153, 11.98)],
        k(.original, .dark, .solid): [.subtle: c(1.00, 0.027, 2.99), .vivid: c(1.00, 0.065, 6.96), .bold: c(1.00, 0.116, 11.99)],
        k(.original, .dark, .glass): [.subtle: c(0.36, 0.038, 3.02), .vivid: c(0.37, 0.089, 7.02), .bold: c(0.38, 0.154, 12.01)],
        k(.original, .dark, .frosted): [.subtle: c(0.46, 0.038, 3.01), .vivid: c(0.47, 0.089, 7.01), .bold: c(0.48, 0.154, 12.00)],
        k(.midnightCobalt, .light, .solid): [.subtle: c(1.00, 0.033, 2.96), .vivid: c(1.00, 0.078, 7.01), .bold: c(1.00, 0.133, 11.99)],
        k(.midnightCobalt, .light, .glass): [.subtle: c(0.25, 0.034, 3.00), .vivid: c(0.27, 0.080, 7.03), .bold: c(0.28, 0.137, 12.00)],
        k(.midnightCobalt, .light, .frosted): [.subtle: c(0.33, 0.034, 2.98), .vivid: c(0.34, 0.080, 6.99), .bold: c(0.35, 0.138, 12.04)],
        k(.midnightCobalt, .dark, .solid): [.subtle: c(1.00, 0.024, 3.03), .vivid: c(1.00, 0.056, 6.97), .bold: c(1.00, 0.102, 11.95)],
        k(.midnightCobalt, .dark, .glass): [.subtle: c(0.35, 0.031, 3.04), .vivid: c(0.35, 0.071, 6.96), .bold: c(0.35, 0.122, 11.96)],
        k(.midnightCobalt, .dark, .frosted): [.subtle: c(0.45, 0.031, 2.99), .vivid: c(0.45, 0.072, 6.96), .bold: c(0.45, 0.124, 11.99)],
        k(.porcelainVapor, .light, .solid): [.subtle: c(1.00, 0.043, 3.03), .vivid: c(1.00, 0.100, 7.00), .bold: c(1.00, 0.173, 11.98)],
        k(.porcelainVapor, .light, .glass): [.subtle: c(0.24, 0.043, 2.97), .vivid: c(0.24, 0.104, 7.02), .bold: c(0.24, 0.183, 12.00)],
        k(.porcelainVapor, .light, .frosted): [.subtle: c(0.31, 0.043, 2.97), .vivid: c(0.31, 0.103, 6.97), .bold: c(0.31, 0.183, 12.02)],
        k(.porcelainVapor, .dark, .solid): [.subtle: c(1.00, 0.034, 3.04), .vivid: c(1.00, 0.081, 7.02), .bold: c(1.00, 0.143, 12.00)],
        k(.porcelainVapor, .dark, .glass): [.subtle: c(0.40, 0.043, 2.99), .vivid: c(0.43, 0.103, 7.03), .bold: c(0.48, 0.179, 11.99)],
        k(.porcelainVapor, .dark, .frosted): [.subtle: c(0.51, 0.043, 2.97), .vivid: c(0.53, 0.103, 6.98), .bold: c(0.57, 0.180, 11.98)],
        k(.smokedUmber, .light, .solid): [.subtle: c(1.00, 0.040, 2.99), .vivid: c(1.00, 0.093, 6.98), .bold: c(1.00, 0.159, 12.01)],
        k(.smokedUmber, .light, .glass): [.subtle: c(0.25, 0.036, 3.04), .vivid: c(0.25, 0.083, 7.02), .bold: c(0.25, 0.142, 12.03)],
        k(.smokedUmber, .light, .frosted): [.subtle: c(0.33, 0.036, 3.02), .vivid: c(0.33, 0.083, 6.99), .bold: c(0.33, 0.142, 11.97)],
        k(.smokedUmber, .dark, .solid): [.subtle: c(1.00, 0.023, 2.95), .vivid: c(1.00, 0.054, 7.06), .bold: c(1.00, 0.093, 12.00)],
        k(.smokedUmber, .dark, .glass): [.subtle: c(0.38, 0.033, 2.96), .vivid: c(0.41, 0.077, 6.98), .bold: c(0.45, 0.130, 11.96)],
        k(.smokedUmber, .dark, .frosted): [.subtle: c(0.48, 0.033, 2.96), .vivid: c(0.50, 0.077, 6.96), .bold: c(0.54, 0.130, 11.96)],
        k(.electricBlue, .light, .solid): [.subtle: c(1.00, 0.036, 2.96), .vivid: c(1.00, 0.085, 7.00), .bold: c(1.00, 0.146, 12.02)],
        k(.electricBlue, .light, .glass): [.subtle: c(0.24, 0.039, 3.04), .vivid: c(0.24, 0.091, 7.04), .bold: c(0.25, 0.157, 12.02)],
        k(.electricBlue, .light, .frosted): [.subtle: c(0.31, 0.039, 3.03), .vivid: c(0.31, 0.091, 7.03), .bold: c(0.32, 0.157, 12.00)],
        k(.electricBlue, .dark, .solid): [.subtle: c(1.00, 0.028, 3.05), .vivid: c(1.00, 0.068, 6.98), .bold: c(1.00, 0.122, 12.00)],
        k(.electricBlue, .dark, .glass): [.subtle: c(0.36, 0.040, 3.03), .vivid: c(0.37, 0.093, 6.97), .bold: c(0.39, 0.162, 11.99)],
        k(.electricBlue, .dark, .frosted): [.subtle: c(0.46, 0.040, 3.02), .vivid: c(0.47, 0.094, 7.01), .bold: c(0.49, 0.163, 12.03)],
        k(.seaGlass, .light, .solid): [.subtle: c(1.00, 0.038, 2.99), .vivid: c(1.00, 0.090, 7.02), .bold: c(1.00, 0.155, 11.97)],
        k(.seaGlass, .light, .glass): [.subtle: c(0.24, 0.033, 3.01), .vivid: c(0.24, 0.078, 7.04), .bold: c(0.24, 0.135, 11.99)],
        k(.seaGlass, .light, .frosted): [.subtle: c(0.31, 0.033, 3.01), .vivid: c(0.31, 0.078, 7.04), .bold: c(0.31, 0.135, 11.98)],
        k(.seaGlass, .dark, .solid): [.subtle: c(1.00, 0.024, 2.97), .vivid: c(1.00, 0.058, 7.00), .bold: c(1.00, 0.102, 11.96)],
        k(.seaGlass, .dark, .glass): [.subtle: c(0.40, 0.032, 3.03), .vivid: c(0.44, 0.074, 7.00), .bold: c(0.50, 0.127, 12.00)],
        k(.seaGlass, .dark, .frosted): [.subtle: c(0.50, 0.032, 3.01), .vivid: c(0.54, 0.074, 6.97), .bold: c(0.59, 0.127, 11.97)],
        k(.amethyst, .light, .solid): [.subtle: c(1.00, 0.024, 3.03), .vivid: c(1.00, 0.055, 6.97), .bold: c(1.00, 0.094, 11.96)],
        k(.amethyst, .light, .glass): [.subtle: c(0.25, 0.023, 2.96), .vivid: c(0.27, 0.054, 6.94), .bold: c(0.29, 0.093, 11.97)],
        k(.amethyst, .light, .frosted): [.subtle: c(0.33, 0.023, 2.95), .vivid: c(0.34, 0.055, 7.06), .bold: c(0.36, 0.093, 11.94)],
        k(.amethyst, .dark, .solid): [.subtle: c(1.00, 0.020, 2.98), .vivid: c(1.00, 0.048, 7.04), .bold: c(1.00, 0.083, 11.97)],
        k(.amethyst, .dark, .glass): [.subtle: c(0.37, 0.024, 3.03), .vivid: c(0.37, 0.055, 6.96), .bold: c(0.37, 0.095, 12.03)],
        k(.amethyst, .dark, .frosted): [.subtle: c(0.47, 0.024, 3.01), .vivid: c(0.47, 0.056, 7.04), .bold: c(0.47, 0.095, 11.95)],
    ]

    static let clampedCellDescriptions: [String] = [
    ]
}
